// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXjh9mO1eyJhM4IF1cO726SzrSwAo85tI',
    appId: '1:212659433738:web:875cb4c6ebc33dcc33caf3',
    messagingSenderId: '212659433738',
    projectId: 'rent-schedule',
    authDomain: 'rent-schedule.firebaseapp.com',
    storageBucket: 'rent-schedule.firebasestorage.app',
    measurementId: 'G-047VZSES97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAECjx_hw5WQMbV2-7nygL8nSHL05Q9wXs',
    appId: '1:212659433738:android:bf7a8d708c5726a633caf3',
    messagingSenderId: '212659433738',
    projectId: 'rent-schedule',
    storageBucket: 'rent-schedule.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7ItwMX57BuDEA0j-jy9ji6X2WVPskdkg',
    appId: '1:212659433738:ios:595fd813ff006c7033caf3',
    messagingSenderId: '212659433738',
    projectId: 'rent-schedule',
    storageBucket: 'rent-schedule.firebasestorage.app',
    androidClientId: '212659433738-mupg7aqaueosscih8ghbmc8suf8gbe59.apps.googleusercontent.com',
    iosClientId: '212659433738-2if851p6irdh2tkaugulmf4mrql74nco.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentschedule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7ItwMX57BuDEA0j-jy9ji6X2WVPskdkg',
    appId: '1:212659433738:ios:595fd813ff006c7033caf3',
    messagingSenderId: '212659433738',
    projectId: 'rent-schedule',
    storageBucket: 'rent-schedule.firebasestorage.app',
    androidClientId: '212659433738-mupg7aqaueosscih8ghbmc8suf8gbe59.apps.googleusercontent.com',
    iosClientId: '212659433738-2if851p6irdh2tkaugulmf4mrql74nco.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentschedule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXjh9mO1eyJhM4IF1cO726SzrSwAo85tI',
    appId: '1:212659433738:web:a6d7c802ae68d0d033caf3',
    messagingSenderId: '212659433738',
    projectId: 'rent-schedule',
    authDomain: 'rent-schedule.firebaseapp.com',
    storageBucket: 'rent-schedule.firebasestorage.app',
    measurementId: 'G-5DRZT0XE30',
  );
}
